# Generated by Django 5.1.4 on 2025-01-20 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aeropuerto',
            fields=[
                ('id_aeropuerto', models.AutoField(primary_key=True, serialize=False)),
                ('estacion_aeropuerto', models.CharField(max_length=3, unique=True)),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('ciudad', models.CharField(max_length=80)),
                ('pais', models.CharField(max_length=80)),
                ('tipo_aeropuerto', models.CharField(blank=True, choices=[('Internacional', 'Internacional'), ('Nacional', 'Nacional')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(choices=[('Administrador', 'Administrador'), ('KAM', 'KAM'), ('Supervisor', 'Supervisor')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('contrasenia', models.CharField(max_length=300, unique=True)),
                ('id_aeropuerto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.aeropuerto')),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.role')),
            ],
        ),
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id_vuelo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_vuelo', models.DateField()),
                ('codigo_del_vuelo', models.CharField(max_length=15)),
                ('destino_vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vuelos_destino', to='website.aeropuerto')),
                ('origen_vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vuelos_origen', to='website.aeropuerto')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_evento', models.CharField(choices=[('SPI', 'SPI'), ('NO SPI', 'NO SPI')], max_length=10)),
                ('observacion', models.CharField(max_length=250)),
                ('evento_lir', models.CharField(max_length=3)),
                ('evento_pax', models.CharField(max_length=3)),
                ('id_vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.vuelo')),
            ],
        ),
        migrations.CreateModel(
            name='Atraso',
            fields=[
                ('id_atraso', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_atraso', models.DateField()),
                ('codigo_atraso', models.CharField(max_length=5)),
                ('motivo_atraso', models.CharField(max_length=100)),
                ('id_vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.vuelo')),
            ],
        ),
    ]
