# Generated by Django 5.1.4 on 2025-01-14 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='aeropuerto',
            fields=[
                ('id_aeropuerto', models.AutoField(primary_key=True, serialize=False)),
                ('estacion_aeropuerto', models.CharField(max_length=3)),
                ('nombre', models.CharField(max_length=80)),
                ('ciudad', models.CharField(max_length=80)),
                ('pais', models.CharField(max_length=80)),
            ],
        ),
    ]
