# Generated by Django 5.1.4 on 2025-01-23 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='nombre_rol',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('KAM_Nacional', 'KAM_Nacional'), ('KAM', 'KAM'), ('Supervisor', 'Supervisor'), ('OJT', 'OJT'), ('Empleados', 'Empleados')], max_length=50),
        ),
    ]
