# Generated by Django 5.1.4 on 2025-01-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_role_nombre_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='nombre_rol',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('KAM', 'KAM'), ('Supervisor', 'Supervisor')], max_length=50),
        ),
    ]
