# Generated by Django 5.1.4 on 2025-01-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_aeropuerto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aeropuerto',
            name='estacion_aeropuerto',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='aeropuerto',
            name='nombre',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
