# Generated by Django 5.1.4 on 2025-01-14 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_aeropuerto_estacion_aeropuerto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('apellido', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('contrasenia', models.CharField(max_length=300, unique=True)),
                ('id_aeropuerto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.aeropuerto')),
                ('id_rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.roles')),
            ],
        ),
    ]
