# Generated by Django 5.1.4 on 2025-01-14 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vuelo',
            fields=[
                ('id_vuelo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_vuelo', models.DateField()),
                ('codigo_del_vuelo', models.CharField(max_length=15)),
                ('destino_vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vuelos_destino', to='website.aeropuerto')),
                ('origen_vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vuelos_origen', to='website.aeropuerto')),
            ],
        ),
    ]
