# Generated by Django 5.1.4 on 2025-01-14 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_vuelo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id_evento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_evento', models.CharField(choices=[('SPI', 'SPI'), ('NO SPI', 'NO SPI')], max_length=10)),
                ('observacion', models.CharField(max_length=250)),
                ('evento_lir', models.CharField(max_length=3)),
                ('evento_pax', models.CharField(max_length=3)),
                ('id_vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.vuelo')),
            ],
        ),
    ]
