# Generated by Django 5.1.4 on 2025-01-14 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_evento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atraso',
            fields=[
                ('id_atraso', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_atraso', models.DateField()),
                ('codigo_atraso', models.CharField(max_length=5)),
                ('motivo_atraso', models.CharField(max_length=100)),
                ('id_vuelo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.vuelo')),
            ],
        ),
    ]
