# Generated by Django 5.1.4 on 2025-01-14 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_atraso'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Roles',
            new_name='Role',
        ),
    ]
