# Generated by Django 5.1.4 on 2025-01-15 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_rename_roles_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='aeropuerto',
            name='tipo_aeropuerto',
            field=models.CharField(blank=True, choices=[('Internacional', 'Internacional'), ('Nacional', 'Nacional')], max_length=20, null=True),
        ),
    ]
